### PR TITLE
doc: update setup.md

### PR DESCRIPTION
**Pull request by minhtrancccp**
include a note on how to set up for bash session with ble.sh enabled

### CODE REVIEW

**Comment by rsteube** [comment]
Seems the environment variables changed a bit.

**Comment by minhtrancccp** [comment]
hi, does that mean `carapace` is not guaranteed to work with `ble.sh`, or how should my phrasing in the pr be changed? many thanks.

**Comment by rsteube** [comment]
When `ble.sh` is enabled it sets some environment variables (`_ble*`). `carapace` uses these for automatic detection.
So `capace _carapace` should  work, but seems something changed in `ble.sh` which broke the detection.

**Comment by minhtrancccp** [comment]
i tried the new commit of carapace and it did work without me specifying `bash-ble`, thanks a lot.

i think the note is redundant for the next release of `carapace-bin`, but it can be changed as some sort of instruction for trouble fixing.

regarding ble.sh's env vars, here are the ones i got when i run `printenv | rg 'ble.*='`:
```sh
bleopt_connect_tty=1
_ble_util_fdlist_cloexec=
_ble_util_fdvars_export=
```

apparently [`_bleopt_connect_tty` is no longer in use](https://github.com/search?q=repo%3Aakinomyoga%2Fble.sh+_bleopt_connect_tty&type=code), but [`bleopt_connect_tty` is.](https://github.com/search?q=repo%3Aakinomyoga%2Fble.sh+bleopt_connect_tty&type=code)

also, it would be great if i can install the new version just by running `go install github.com/carapace-sh/carapace-bin@master` instead of cloning the repo and build a binary from there.

again, thanks a lot for your work and speedy updates.

**Comment by rsteube** [comment]
Yeah, I think a troubleshooting page might be good.

`go install` sadly isn't possible as it doesn't support `go generate`.

**Pull request closed without merging**
